openapi: 3.0.0
info:
  version: 1.0.0
  title: Superheroes
  license:
    name: MIT
paths:
  /heroes:
    get:
      summary: List all superheroes
      operationId: listHeroes
      tags:
        - superheroes
      responses:
        '200':
          description: An array of superheroes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Heroes'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a superhero
      operationId: createHero
      tags:
        - superheroes
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Hero'
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/heroes/{heroId}':
    get:
      summary: Info for a specific superhero
      operationId: showHeroById
      tags:
        - superheroes
      parameters:
        - name: heroId
          in: path
          required: true
          description: The id of the superhero to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hero'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Hero:
      required:
        - name
        - pseudonym
        - publisher
        - skills
        - allies
        - dateOfFirstAppearance
      properties:
        id:
          type: string
        name:
          type: string
        pseudonym:
          type: string
        publisher:
          type: string
        skills:
          type: array
          items:
            type: string
        allies:
          type: array
          items:
            type: string
        dateOfFirstAppearance:
          type: string
    Heroes:
      type: array
      items:
        $ref: '#/components/schemas/Hero'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
